---
_id: aad4b690-a2dd-11e9-9aab-f5cac39b1a42
metadata:
  author:
    first: Shubhajit
    last: Mondal
    email: sm44@iitbbs.ac.in
    github_id: smondal44
  timestamp: '13 August, 2019'
  summary: >-
    In this problem, we solve the linear elasticity problem for circular
    homogeneous precipitate in effectively infinite domain.
  implementation:
    name: Fenics
    repo:
      url: 'https://github.com/smondal44/Linear-Elasticity/blob/master/r_Cir_ho_s.py'
      version: 13d33ae6a2b729ea007c16311799f64cc34703fe
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: non-gpu
    parallel_model: serial
    clock_rate: '2.4'
    cores: '1'
    nodes: '1'
benchmark:
  id: 4a
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '36000'
        sim_time: '36000'
  - name: memory_usage
    values:
      - unit: KB
        value: '8388608'
  - name: contour
    url: 'https://drive.google.com/open?id=1QCbHstjM024FaGELPsU2KYIN9Owddr62'
    format:
      type: csv
      parse:
        x: number
        'y': number
    description: >-
      The equilibrium data contains the coordinate of the contour plot at
      equilibrium. We plot the contour plot at the value of order parameter is
      equal to 0.5.
    type: line
    transform:
      - type: formula
        expr: datum.x
        as: x
      - type: formula
        expr: datum.y
        as: 'y'
  - name: all_data
    url: 'https://drive.google.com/open?id=1GDX3YSUwq7-UrMDcy8e-fyTYZthYlmoX'
    format:
      type: csv
      parse:
        Time: number
        "Total Energy": number
    description: >-
      Here, the data file includes the time, elastic, bulk, gradient and total
      free energy of the system.
    type: line
    transform:
      - type: formula
        expr: datum.Time
        as: x
      - type: formula
        expr: "datum['Total Energy']"
        as: 'y'
  - name: Energy_plot1
    url: 'https://drive.google.com/open?id=1AEuagAOSrmO3Zi1SjYTbavTodGCITRLx'
    type: image
    description: 'Here, we are plotting the elastic energy as a function of time.'
  - name: Energy_plot2
    url: 'https://drive.google.com/open?id=1LMCWTaSS2YsQG2pE7gu2IyEmHVStFMJK'
    type: image
    description: >-
      Here, we are plotting the total free energy of the system as a function of
      time.
date: 1562740855
